spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: virgoplatform.info@gmail.com
    password: ${MAIL_PSWD}
    properties:
      smtp:
        timeout: 3000
        auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username:  ${DB_USER}
    password:  ${DB_PSWD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #storage_engine: innodb


#spring:
#  thymeleaf:
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#  datasource:
#    url: jdbc:postgresql://localhost:5432/virgoapplication
#    username: postgres
#    password: password
#  jpa:
#    hibernate:
#      ddl-auto: update
#server:
 # servlet:
 #   context-path: "/site"