spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virgoapplication
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    rest:
      basePath: /site