#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://aws.connect.psdb.cloud/virgoapplication
#   # username: 53cu7vy3p0yjcrt4nmiu virgouser
#    #password: pscale_pw_kuuNJmodYMIhlOSpZsR4esgwnWXAmGUhH2vRGHS4lxh
#    username: rnmtn7m3nc6tu91iylb8 #virgoadmin
#    password: pscale_pw_gM7yVGefiS0SHQCPf7fwg5YbjmWt2THxc14q83ZGHY7
#  jpa:
#    hibernate.ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        #storage_engine: innodb

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/virgoapplication
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
#server:
 # servlet:
 #   context-path: "/site"